CoolBitX-Technology/sygna-bridge-assembly

cryptocurrency/sygna:0x8000003c.0x0000000000085d4780b73119b644ae5ecd22b376.json
cryptocurrency/sygna:0x8000003c.0x00000000441378008ea67f4284a57932b1c000a5.json
cryptocurrency/sygna:0x8000003c.0x319ad3ff82bedddb3bc85fd7943002d25cdb3cb9.json
cryptocurrency/sygna:0x8000003c.0x3506424f91fd33084466f402d5d97f05f8e3b4af.json
cryptocurrency/sygna:0x8000003c.0x4ddc2d193948926d02f9b1fe9e1daa0718270ed5.json
cryptocurrency/sygna:0x8000003c.0x4fabb145d64652a948d72533023f6e7a623c7c53.json
cryptocurrency/sygna:0x8000003c.0x743c79f88dcadc6e7cfd7fa2bd8e2bfc68dae053.json
cryptocurrency/sygna:0x8000003c.0x80fb784b7ed66730e8b1dbd9820afd29931aab03.json
cryptocurrency/sygna:0x8000003c.0x888666ca69e0f178ded6d75b5726cee99a87d698.json
cryptocurrency/sygna:0x8000003c.0x89d24a6b4ccb1b6faa2625fe562bdd9a23260359.json
cryptocurrency/sygna:0x8000003c.0x8e4d222dbd4f8f9e7c175e77d6e71715c3da78e0.json
cryptocurrency/sygna:0x8000003c.0x8ed876e408959643479534a21970ec023d0fb51e.json
cryptocurrency/sygna:0x8000003c.0x998ffe1e43facffb941dc337dd0468d52ba5b48a.json
cryptocurrency/sygna:0x8000003c.0xa74476443119a942de498590fe1f2454d7d4ac0d.json
cryptocurrency/sygna:0x8000003c.0xb62132e35a6c13ee1ee0f84dc5d40bad8d815206.json
cryptocurrency/sygna:0x8000003c.0xb8c77482e45f1f44de1745f52c74426c631bdd52.json
cryptocurrency/sygna:0x8000003c.0xc08512927d12348f6620a698105e1baac6ecd911.json
cryptocurrency/sygna:0x8000003c.0xc56c2b7e71b54d38aab6d52e94a04cbfa8f604fa.json
cryptocurrency/sygna:0x8000003c.0xd6d69a3d5e51dbc2636dc332338765fcca71d5d5.json
cryptocurrency/sygna:0x8000003c.0xd86a0b407e2c378f6eced3c4b84f91a7f491aaee.json
cryptocurrency/sygna:0x8000003c.0xe435502c85a4e7e79cfab4167af566c27a7a0784.json
cryptocurrency/sygna:0x8000003c.0xfdde0a92bfef2d95695d32400a0a8f55e530dc67.json

- ZIL	sygna:0x8000003c.0xfd8971d5e8e1740ce2d0a84095fca4de729d0c16 
- DASH	sygna:0x80000005
- ZEC	sygna:0x80000085
are existed in the test environment.

feat: add new currencies

---

UNRELEASE.md

feat:release 1.18.0

---

cryptocurrency/sygna-0x8000022f.json
cryptocurrency/sygna:0x8000009b.json

fix: currency 0x8000022f

---

cryptocurrency/sygna-0x8000232e.0xda2230c7b52a4249e69c604c43fa5db57809be33.json

fix: del NBX

---

cryptocurrency/sygna-0x8000232d.0x6e84a6216eA6dACC71eE8E6b0a5B7322EEbC0fDd.json
cryptocurrency/sygna-0x8000232d.0x6e84a6216ea6dacc71ee8e6b0a5b7322eebc0fdd.json
cryptocurrency/sygna-0x8000232d.0x8729438EB15e2C8B576fCc6AeCdA6A148776C0F5.json
cryptocurrency/sygna-0x8000232d.0x8729438eb15e2c8b576fcc6aecda6a148776c0f5.json
cryptocurrency/sygna-0x8000232e.0x3019BF2a2eF8040C242C9a4c5c4BD4C81678b2A1.json
cryptocurrency/sygna-0x8000232e.0x3019bf2a2ef8040c242c9a4c5c4bd4c81678b2a1.json
cryptocurrency/sygna-0x8000232e.0x8C851d1a123Ff703BD1f9dabe631b69902Df5f97.json
cryptocurrency/sygna-0x8000232e.0x8c851d1a123ff703bd1f9dabe631b69902df5f97.json
cryptocurrency/sygna-0x8000232e.0xD40bEDb44C081D2935eebA6eF5a3c8A31A1bBE13.json
cryptocurrency/sygna-0x8000232e.0xd40bedb44c081d2935eeba6ef5a3c8a31a1bbe13.json

fix: lower case

---

UNRELEASE.md
cryptocurrency/sygna-0x8000003c.0x1a3496c18d558bd9c6c8f609e1b129f67ab08163.json
cryptocurrency/sygna-0x8000003c.0x8ca328bb08b0ab920e792e5c67b718de4330fc9d.json

release: 1.21.0

---

cryptocurrency/sygna:0x8000003c.0x1a3496c18d558bd9c6c8f609e1b129f67ab08163.json

fix: remove duplicate token

---

cryptocurrency/sygna-0x8000003c.0x7420b4b9a0110cdc71fb720908340c03f9bc03ec.json

feat: SYGN-3476 add JASMY

---

UNRELEASE.md
cryptocurrency/sygna-0x8000003c.0x0f28a3a8a5a17f28a7bfae70dccf12a596c5674c.json
cryptocurrency/sygna-0x8000003c.0x335ad06475785736dbe149242537e560cb5a5702.json
cryptocurrency/sygna-0x8000003c.0x5cac718a3ae330d361e39244bf9e67ab17514ce8.json
cryptocurrency/sygna-0x8000003c.0x6aa9bcf20ae2fcb9a29d7d99c624d9db43d93969.json
cryptocurrency/sygna-0x8000003c.0xadbbb02e20c44779e87f7ea90c47c9a7a8a93fee.json
cryptocurrency/sygna-0x8000003c.0xc08e7911ee27169967ed8ec252fee73048cc0dff.json
cryptocurrency/sygna-0x8000003c.0xf83301c5cd1ccbb86f466a6b3c53316ed2f8465a.json
cryptocurrency/sygna-0x800003c6.0x204820b6e6feae805e376d2c6837446186e57981.json

release:  new currencies

---

cryptocurrency/sygna:0x80000005.json
cryptocurrency/sygna:0x80000085.json

feat: SYGN-1474

---

cryptocurrency/sygna-0x800001f5.epjfwdd5aufqssqem2qn1xzybapc8g4weggkzwytdt1v.json
cryptocurrency/sygna-0x800003c6.0x3c499c542cEF5E3811e1192ce70d8cC03d5c3359.json
cryptocurrency/sygna-0x8000232d.0xb97ef9ef8734c71904d8002f8b6bc66dd9c48a6e.json
cryptocurrency/sygna:0x80000094.ga5zsejyb37jrc5avcia5mop4rhtm335x2kgx3ihojapp5re34k4kzvn.json
cryptocurrency/sygna:0x80000162.1337.json

新增其他鏈的 usdc: Solana, Polkadot, AVAX, Polygon Pos, Stellar

feat: SYGN-10910 add another token of usdc

---

coingecko_id/mapping.json

新增 coingecko_id
之後若要上線新幣
除了在本來的 cryptocurrency 底下新增 json 檔案
也要在 coingecko_id 底下新增對應的 `currency_id -> coingecko_id` mapping

fix: SYGN-10908 update coingecko_id to json files

---

coingecko_id/mapping.json
cryptocurrency/sygna:0x8000003c.0x6D614686550B9E1c1DF4b2cD8f91C9D4df66C810.json
cryptocurrency/sygna:0x80000d05.json

新增 SXP on Solar, SKEB on Ethereum

feat: Add SXP-on-Solar and SKEB-on-Ethereum

---

cryptocurrency/sygna:0x8000003c.0x6D614686550B9E1c1DF4b2cD8f91C9D4df66C810.json
cryptocurrency/sygna:0x80000d05.json

Sygn 11670 add sxp on solar skeb on ethereum

---

PRELEASE.md

feat: Sygn 11670 add sxp on solar skeb on ethereum: Test-to-Master

---

blockchain_name/mapping.json
coingecko_id/mapping.json
cryptocurrency/sygna-0x80000076.uosmo.json
cryptocurrency/sygna-0x800001f5.8e5pw1g1nqpmgvyes1vzx8lokazvuzgl6g1uhr4ivbab.json
cryptocurrency/sygna-osmosis.json

------------
**Summary**
This pull request introduces new mappings for the "osmosis" token in multiple files and updates existing ones.
**Key Points**
* Adds new mappings to "mapping.json" files in "blockchain\_name" and "coingecko\_id" directories
* Creates new files for "sygna-osmosis.json" and "sygna-0x80000076.uosmo.json" in "cryptocurrency" directory
* Updates "osmosis" token mappings across the project. 

feat: SYGN-13831 new currencies

---

cryptocurrency/sygna-0x80000076.uosmo.json

------------
**Summary**
Adds "addr\_extra\_info" key with value ["memo"] to OSMO currency configuration file's "platform" object.
**Key Points**
* Introduces new key-value pair to OSMO currency config file.
* Value set to ["memo"].
* Affects the "platform" object within the file. 

fix: SYGN-13831 modify currency's extra info

---

coingecko_id/mapping.json
cryptocurrency/sygna-0x8000003c.0x6982508145454ce325ddbe47a25d4ec3d2311933.json
cryptocurrency/sygna-0x8000003c.0x77f57a6b9c9e307c90a9e9065d9cd7c6e92014b6.json

------------
**Summary**
Added two new currencies, "Pepe" and "RegistArtToken", to `mapping.json` and created their JSON representations in `cryptocurrency` directory.
**Key Points**
- Added two new entries to `mapping.json` for currencies "Pepe" and "RegistArtToken"
- Created new files for their respective JSON representations in `cryptocurrency` directory. 

feat: SYGN-14476 new currencies

---

UNRELEASE.md
coingecko_id/mapping.json
cryptocurrency/sygna-0x8000003c.0x6982508145454ce325ddbe47a25d4ec3d2311933.json
cryptocurrency/sygna-0x8000003c.0x77f57a6b9c9e307c90a9e9065d9cd7c6e92014b6.json

------------
**Summary:**
Introduced "Pepe" and "RegistArtToken" currencies with COingecko IDs, updated UNRELEASE.md, and added files for new currencies.
**Key Points:**
1. Added two new currencies, "Pepe" and "RegistArtToken".
2. Updated UNRELEASE.md with new tag [1.33.0-alpha.1] and commit.
3. Added currencies to coingecko\_id/mapping.json and created JSON files. 

release: new currencies

---

cryptocurrency/sygna-0x80002329.json
cryptocurrency/sygna:0x8000003c.0x209c1808febf6c1ab7c65764bb61ad67d3923fcc.json
cryptocurrency/sygna:0x80000080.json

------------
**Overview**
This PR removes three unused cryptocurrency asset files (`sygna-0x80002329.json`, `sygna:0x8000003c.0x209c1808febf6c1ab7c65764bb61ad67d3923fcc.json`, and `sygna:0x80000080.json`) to clean up the project.  These assets represent ARB on Arbitrum (ARB1), APEcoin (APE), and Monero (XMR).
**Key Changes**
- Deleted the JSON files for the unused cryptocurrency assets.
**Recommendations**
Ready to merge.  The change is straightforward and low risk.

feat: SYGN-14475 remove unused asset

---

UNRELEASE.md
cryptocurrency/sygna-0x80002329.json
cryptocurrency/sygna:0x8000003c.0x209c1808febf6c1ab7c65764bb61ad67d3923fcc.json
cryptocurrency/sygna:0x80000080.json

------------
**Overview**
This PR removes unused cryptocurrency asset files (`sygna-0x80002329.json`, `sygna:0x8000003c.0x209c1808febf6c1ab7c65764bb61ad67d3923fcc.json`, and `sygna:0x80000080.json`) and updates the `UNRELEASE.md` file with release notes for version 1.35.0-alpha.1.  This cleanup addresses issue SYGN-14475.
**Key Changes**
- Deleted three JSON files representing unused cryptocurrency assets.
- Updated `UNRELEASE.md` to document the removal of these assets for the 1.35.0-alpha.1 release.
**Recommendations**
Ready to merge after verifying the removed assets are indeed unused and the release notes in `UNRELEASE.md` are accurate.
<h6>To turn off PR summary, please visit <a href="https://app.typoapp.io/settings/dev-analytics/notification?tab=codeHealth">Not …

release: remove unused assets

---

coingecko_id/mapping.json
cryptocurrency/sygna-0x8000003c.0x58b6a8a3302369daec383334672404ee733ab239.json

------------
**Overview**
This PR adds support for the Livepeer (LPT) cryptocurrency by including its details in the project.  The `coingecko_id/mapping.json` file is updated to map the Livepeer currency ID to its CoinGecko ID.
**Key Changes**
- Added a new JSON file containing Livepeer's currency information (`cryptocurrency/sygna-0x8000003c.0x58b6a8a3302369daec383334672404ee733ab239.json`).
- Updated `coingecko_id/mapping.json` to include the mapping for Livepeer.
**Recommendations**
Ready to merge after verifying the accuracy of the added Livepeer information and the correctness of the mapping in `coingecko_id/mapping.json`.
<h6>To turn off PR summary, please visit <a href="https://app.typoapp.io/settings/dev-analytics/notification?tab=codeHealth">Notification …

feat: SYGN-15302 new currencies

---

UNRELEASE.md
coingecko_id/mapping.json
cryptocurrency/sygna-0x8000003c.0x58b6a8a3302369daec383334672404ee733ab239.json

------------
**Overview:**
This PR adds support for Livepeer (LPT) by including its details in `coingecko_id/mapping.json` and creating a new cryptocurrency file `sygna-0x8000003c.0x58b6a8a3302369daec383334672404ee733ab239.json`. It also updates the `UNRELEASE.md` file with release notes.
**Key Changes:**
- Added Livepeer (LPT) to the Coingecko ID mapping.
- Created a new JSON file with Livepeer's currency details.
- Updated `UNRELEASE.md` with a new release entry.
**Recommendations:**
Stable for release.  The changes are straightforward and well-contained, focusing on adding a new currency definition.  No apparent negative impact is expected.
<h6>To turn off PR summary, please visit <a href="https://app.typoapp.io/settings/notification?tab=codeHealth">Notification …

feat: dev to test

---

coingecko_id/mapping.json
cryptocurrency/sygna:fcrcoin.json

feat SYGN-16144 add FCR coin
------------
**Overview**
This PR adds support for FCR Coin (FCR) by including its details in the `coingecko_id/mapping.json` and creating a new file `cryptocurrency/sygna:fcrcoin.json` with the coin's information.
**Key Changes**
- Added a new entry for FCR Coin in `coingecko_id/mapping.json`, mapping the `sygna:fcrcoin` currency ID to the `fcr-coin` Coingecko ID.
- Created `cryptocurrency/sygna:fcrcoin.json` containing FCR Coin's details, including name, symbol, and active status.
- Modified existing entries to include "sygna:" prefix.
**Recommendations**
Ready for deployment. The changes are straightforward and effectively add support for the new coin.
| Category    | Lines Changed |
|-------------|---------------|
| New Work    | 5 …

feat SYGN-16144 add FCR coin

---

UNRELEASE.md
blockchain_name/mapping.json
coingecko_id/mapping.json
cryptocurrency/sygna:fcrcoin.json

feat :SYGN-16144 ADD FCR
------------
**Overview:**
This PR adds support for FCR Coin (FCR) by including it in the `coingecko_id/mapping.json` file and creating a new entry in `cryptocurrency/sygna:fcrcoin.json`. It also updates the `UNRELEASE.md` file with release notes.
**Key Changes:**
- Added a new mapping for FCR Coin in `coingecko_id/mapping.json`, linking its currency ID (`sygna:fcrcoin`) to its CoinGecko ID (`fcr-coin`).
- Created a new JSON file, `cryptocurrency/sygna:fcrcoin.json`, containing details about FCR Coin, such as its name, symbol, and active status.
- Updated `UNRELEASE.md` to document the addition of FCR Coin for the upcoming release.
- Modified existing entries in `coingecko_id/mapping.json` to include the "sygna:" prefix for consistency. …

feat :SYGN-16144 ADD FCR

---

coingecko_id/mapping.json
cryptocurrency/sygna-0x8000003c.0x56072c95faa701256059aa122697b133aded9279.json

------------
**Overview:** This PR adds support for the Sky (SKY) cryptocurrency by including its details in the `coingecko_id/mapping.json` and creating a new file `sygna-0x8000003c.0x56072c95faa701256059aa122697b133aded9279.json` with the currency's information.
**Key Changes:**
- Added a new mapping for SKY in `coingecko_id/mapping.json`, linking its Sygna ID to its CoinGecko ID.
- Created a new JSON file containing details about SKY, including its name, symbol, platform, and active status.
**Recommendations:**
Ready for deployment. The changes are straightforward and well-defined, introducing a new currency listing with necessary information.
| Category    | Lines Changed |
|-------------|---------------|
| New Work    | 5 (100%)      |
| Total Changes | 5 …

feat: SYGN-16962 new currency

---

UNRELEASE.md
coingecko_id/mapping.json
cryptocurrency/sygna-0x8000003c.0x56072c95faa701256059aa122697b133aded9279.json

------------
**Overview:** This PR adds support for the Sky (SKY) cryptocurrency by including its details in the `coingecko_id/mapping.json` and creating a new JSON file with the currency's specifications. It also updates the unreleased changelog.
**Key Changes:**
- Added a new mapping for the Sky (SKY) cryptocurrency in `coingecko_id/mapping.json`, linking its Sygna ID to its CoinGecko ID.
- Created a new file `cryptocurrency/sygna-0x8000003c.0x56072c95faa701256059aa122697b133aded9279.json` containing details about the SKY cryptocurrency, such as its name, symbol, platform, and token address.
- Updated `UNRELEASE.md` with a new entry for version 1.41.0-alpha.1, documenting the addition of the SKY currency.
**Recommendations:**
Ready for deployment. The changes are …

release: new currency
